### ISSUE TITLE
Ping

### ISSUE THREAD

**Issue by tigca** [nm17/nicevk#10]
Что-то обновлений нету 😔

**Comment by nm17** [comment]
Ку, к сожалению, проект заброшен мною т.к сейчас почти не пишу на питоне, но ты вполне можешь сделать fork моего репозитория. Извини что так поздно ответил. Если тебе интересно что-то ещё, можешь мне написать в тг https://t.me/nvrm17

**Comment by nm17** [comment]
@tigca пинг на всякий случай, а то я сам упустил уведомление

**Comment by tigca** [comment]
@nm17, спасибо, буду делать форк
