### ISSUE TITLE
Disturbing captcha handling

### ISSUE THREAD

**Issue by timoniq** [nm17/nicevk#4]
А для чего `error_handler.captcha_handler`? Именно для этого

**Comment by nm17** [comment]
19 минут как фичу добавил в доку, уже сразу issue сделал. :+1:

Инфа для меня:
  - https://github.com/timoniq/vkbottle/blob/7fe1bddfbbee73c36181d86f2b6c2e112f94797c/docs/stuff.ru.md#error-handler-1
